INSERT INTO RomanizationRules (rule_id, script_id, standard_name, description, example_native, example_romanized, phoneme_notes, is_phonetic, is_academic, created_at, last_modified_on) VALUES

-- Latin Script Romanization (SC00001)
('RR00001', 'SC00001', 'Classical Latin Standard', 'Standard romanization for Classical Latin following traditional orthography. Latin script is already in Roman alphabet, so this represents canonical spelling conventions from Classical period (c. 100 BCE - 200 CE).', 'Caesar', 'Caesar', 'Classical pronunciation: C always hard [k], AE as diphthong [ae], V represents consonantal /w/. Long vowels marked with macrons in scholarly editions (ā, ē, ī, ō, ū). Diphthongs: ae, oe, au, eu, ei, ui.', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00002', 'SC00001', 'Ecclesiastical Latin Standard', 'Romanization following Medieval and Ecclesiastical Latin pronunciation conventions used in Catholic liturgy and scholarly contexts from Medieval period onward.', 'Caesar', 'Caesar', 'Ecclesiastical pronunciation: C before e/i is [tʃ] (ch sound), AE as [e], V as consonantal [v]. Used in Vatican Latin, liturgical texts, and Neo-Latin contexts. Reflects Italian phonological influence.', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Greek Script Romanization (SC00002)
('RR00003', 'SC00002', 'Modern Greek Transliteration', 'Standard transliteration for Modern Greek following contemporary conventions used in international contexts and scholarly publications.', 'Ἀλέξανδρος', 'Alexandros', 'Eta (η) → ē or i; Upsilon (υ) → y or i; Phi (φ) → f; Chi (χ) → ch; Theta (θ) → th; Omega (ω) → ō or o. Diacritics generally omitted in simplified forms. Reflects Modern Greek pronunciation (Demotic).', TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00004', 'SC00002', 'Ancient Greek (Classical) Standard', 'Scholarly transliteration for Ancient Greek following Classical Attic conventions (5th-4th century BCE). Preserves phonological distinctions lost in Modern Greek.', 'Ἀλέξανδρος', 'Aléxandros', 'Preserves vowel length: ā, ē, ī, ō, ū. Eta (η) → ē [long e]; Omega (ω) → ō [long o]; Upsilon (υ) → y [French u]; Phi (φ) → ph [aspirated p]; Chi (χ) → kh [aspirated k]; Theta (θ) → th [aspirated t]. Rough breathing (῾) → h; Smooth breathing (᾿) omitted. Pitch accents marked: acute (´), grave (`), circumflex (ˆ).', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00005', 'SC00002', 'Beta Code Standard', 'ASCII-based transliteration system used in TLG (Thesaurus Linguae Graecae) and Perseus Digital Library. Designed for computational processing of Greek texts.', 'Ἀλέξανδρος', '*ale/candros', 'Capital letters: *A, *B, etc. Diacritics: / (acute), \\ (grave), = (circumflex), ( (rough breathing), ) (smooth breathing), | (iota subscript), + (diaeresis). Combines diacritics with letters using ASCII symbols. Widely used in digital humanities and ancient text databases.', FALSE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00006', 'SC00002', 'ISO 843 Standard', 'International standard for Greek transliteration (ISO 843:1997). Provides systematic one-to-one mapping between Greek and Latin characters.', 'Ἀλέξανδρος', 'Aléxandros', 'Comprehensive mapping: Α/α → A/a; Β/β → V/v; Γ/γ → G/g; Δ/δ → D/d; Ε/ε → E/e; Ζ/ζ → Z/z; Η/η → I/i; Θ/θ → Th/th; Ι/ι → I/i; Κ/κ → K/k; Λ/λ → L/l; Μ/μ → M/m; Ν/ν → N/n; Ξ/ξ → X/x; Ο/ο → O/o; Π/π → P/p; Ρ/ρ → R/r; Σ/σ/ς → S/s; Τ/τ → T/t; Υ/υ → Y/y; Φ/φ → F/f; Χ/χ → Ch/ch; Ψ/ψ → Ps/ps; Ω/ω → O/o. Diacritics preserved with combining marks in strict mode.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00007', 'SC00002', 'British School at Athens Standard', 'Traditional transliteration system used in British classical scholarship. Emphasizes etymological transparency and pronunciation guidance.', 'Ἀλέξανδρος', 'Aléxandros', 'Eta (η) → ē; Omega (ω) → ō; Upsilon (υ) → y or u (after consonants); Long vowels marked with macron. Aspirated stops: Φ → ph, Χ → ch, Θ → th. Maintains distinction between long and short vowels for scholarly precision.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Phoenician Script Romanization (SC00004)
('RR00008', 'SC00004', 'Academic Phoenician Standard', 'Standard scholarly transliteration for Phoenician script following conventions used in Semitic philology and Northwest Semitic studies.', '𐤇𐤍𐤁𐤏𐤋', 'ḥnbʿl', 'Aleph (𐤀) → ʾ (glottal stop); Beth (𐤁) → b; Gimel (𐤂) → g; Daleth (𐤃) → d; He (𐤄) → h; Waw (𐤅) → w; Zayin (𐤆) → z; Heth (𐤇) → ḥ [pharyngeal fricative]; Teth (𐤈) → ṭ [emphatic t]; Yodh (𐤉) → y; Kaph (𐤊) → k; Lamedh (𐤋) → l; Mem (𐤌) → m; Nun (𐤍) → n; Samekh (𐤎) → s; Ayin (𐤏) → ʿ [pharyngeal voiced]; Pe (𐤐) → p; Sadhe (𐤑) → ṣ [emphatic s]; Qoph (𐤒) → q [uvular stop]; Resh (𐤓) → r; Shin (𐤔) → š [ʃ]; Taw (𐤕) → t. Vowels not represented in abjad, supplied contextually.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00009', 'SC00004', 'SBL Phoenician Standard', 'Society of Biblical Literature transliteration standard for Phoenician, harmonized with Hebrew romanization conventions.', '𐤇𐤍𐤁𐤏𐤋', 'ḥnbʿl', 'Follows SBL Hebrew conventions adapted for Phoenician: Emphatic consonants marked with underdot (ḥ, ṭ, ṣ, q). Pharyngeals: ḥ for Heth, ʿ for Ayin. Glottal stop ʾ for Aleph. Shin → š. Matres lectionis (vowel letters) indicated when present: Waw → ū/ō, Yodh → ī/ē, He → ā (final). Standard for biblical and epigraphic studies.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00010', 'SC00004', 'Punic Conventional Standard', 'Romanization conventions for Punic (Carthaginian Phoenician) reflecting Neo-Punic orthographic developments and Latin transcription traditions.', '𐤇𐤍𐤁𐤏𐤋', 'Hannibal', 'Adapted for Carthaginian context with Latin influence. Simplified system used in classical Latin sources: Heth (𐤇) → H; Ayin (𐤏) → omitted or a/e; Aleph (𐤀) → omitted or a. Reflects how Punic names were transcribed by Roman historians (Livy, Polybius). Emphasizes practical pronunciation over phonemic precision. Common in historical and archaeological publications on Carthage.', FALSE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00011', 'SC00004', 'Phoenician IPA Standard', 'Phonetic transcription of Phoenician using International Phonetic Alphabet. Represents reconstructed pronunciation based on comparative Semitic phonology.', '𐤇𐤍𐤁𐤏𐤋', '[ħannibaʕl]', 'Reconstructed phonemic inventory: /ʔ/ (Aleph), /b/ (Beth), /g/ (Gimel), /d/ (Daleth), /h/ (He), /w/ (Waw), /z/ (Zayin), /ħ/ (Heth - voiceless pharyngeal), /tˤ/ (Teth - emphatic), /j/ (Yodh), /k/ (Kaph), /l/ (Lamedh), /m/ (Mem), /n/ (Nun), /s/ (Samekh), /ʕ/ (Ayin - voiced pharyngeal), /p/ (Pe), /sˤ/ (Sadhe - emphatic), /q/ (Qoph - uvular), /r/ (Resh), /ʃ/ (Shin), /t/ (Taw). Vowels reconstructed: /a/, /i/, /u/ with length distinctions. Used in linguistic reconstruction and comparative studies.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00012', 'SC00004', 'Neo-Punic Simplified Standard', 'Simplified romanization for Late Punic period (3rd century BCE - 2nd century CE) reflecting phonological changes and increased use of matres lectionis.', '𐤇𐤍𐤁𐤏𐤋', 'hnbʿl', 'Reflects Neo-Punic orthographic developments: increased vowel marking using Aleph, He, Waw, Yodh. Phonological mergers: loss of some emphatic contrasts, weakening of laryngeals and pharyngeals in some positions. Simplified consonantal representation reflecting Late Punic pronunciation shifts. Used for inscriptions from Roman North Africa (1st-3rd centuries CE).', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hebrew Script Romanization (SC00005) - Assuming Hebrew is SC00005

('RR00013', 'SC00005', 'Academic Hebrew Standard', 'Traditional academic transliteration for Biblical and Modern Hebrew used in scholarly publications and linguistic analysis.', 'יְרוּשָׁלַיִם', 'Yərūšālayim', 'Full representation of Masoretic pointing. Dagesh forte (doubling) indicated by double consonant. Spirantized forms (BeGaD KeFaT letters): ḇ, ḡ, ḏ, ḵ, p̄, ṯ. Emphatic consonants: ḥ (Het), ṭ (Tet), ṣ (Tsade), q (Qof). Pharyngeal Ayin (ע) → ʿ. Glottal Aleph (א) → ʾ. Shin (שׁ) → š; Sin (שׂ) → ś. Distinguishes all vowel qualities and lengths with diacritics.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

('RR00014', 'SC00005', 'Hebrew IPA Standard', 'Phonetic representation of Hebrew using International Phonetic Alphabet. Distinguishes between Biblical/Tiberian and Modern Israeli pronunciations.', 'יְרוּשָׁלַיִם', '[jəʁuʃaˈlajim]', 'Modern Israeli phonemic inventory: /ʔ/ (Aleph, Ayin - glottal stop or omitted), /b/ (Beth), /v/ (Vet), /g/ (Gimel), /d/ (Dalet), /h/ (He), /v/ (Vav consonant), /z/ (Zayin), /χ/ or /ħ/ (Het - uvular or pharyngeal fricative), /t/ (Tet, Tav), /j/ (Yod), /k/ (Kaf, Qof), /χ/ (Khaf), /l/ (Lamed), /m/ (Mem), /n/ (Nun), /s/ (Samekh, Sin), /p/ (Pe), /f/ (Fe), /ts/ (Tsade), /ʁ/ (Resh - uvular), /ʃ/ (Shin). Vowels: /a/, /e/, /i/, /o/, /u/. Stress marked with ˈ.', TRUE, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),