-- Insert Name Roots extracted from Names in the database
-- These represent atomic linguistic components used to build names
-- Roots are organized by script and linguistic origin

INSERT INTO NameRoots (root_id, root_text, variant_of_id, variant_type, original_script, romanized_form, script_id, notes, is_active, source_reference, created_at, last_modified_on) VALUES

-- Latin Roots (Roman Names)

-- Cognomina Roots
('NR00001', 'caes-', NULL, NULL, 'caes-', 'caes-', 'SC00001', 'Root meaning "cut" or "hair", from caesus/caesaries', TRUE, 'Etymology from Caesar cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00002', 'scaev-', NULL, NULL, 'scaev-', 'scaev-', 'SC00001', 'Root meaning "left-handed", from scaevus', TRUE, 'Etymology from Scaevola cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00003', 'max-', NULL, NULL, 'max-', 'max-', 'SC00001', 'Root meaning "great, large", superlative form', TRUE, 'Etymology from Maximus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00004', 'cinc-', NULL, NULL, 'cinc-', 'cinc-', 'SC00001', 'Root from cincinnus meaning "curly"', TRUE, 'Etymology from Cincinnatus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00005', 'sever-', NULL, NULL, 'sever-', 'sever-', 'SC00001', 'Root meaning "stern, strict"', TRUE, 'Etymology from Severus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00006', 'cicer-', NULL, NULL, 'cicer-', 'cicer-', 'SC00001', 'Root meaning "chickpea"', TRUE, 'Etymology from Cicero cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00007', 'brut-', NULL, NULL, 'brut-', 'brut-', 'SC00001', 'Root meaning "heavy, dull"', TRUE, 'Etymology from Brutus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00008', 'cat-', NULL, NULL, 'cat-', 'cat-', 'SC00001', 'Root meaning "shrewd, wise", from catus', TRUE, 'Etymology from Cato cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00009', 'luc-', NULL, NULL, 'luc-', 'luc-', 'SC00001', 'Root meaning "light", from lux/lucere', TRUE, 'Etymology from Lucius, Lucullus, Lucianus', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00010', 'octav-', NULL, NULL, 'octav-', 'octav-', 'SC00001', 'Root meaning "eighth", from octavus', TRUE, 'Etymology from Octavianus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00011', 'rem-', NULL, NULL, 'rem-', 'rem-', 'SC00001', 'Root possibly from remus "oar" or suckling', TRUE, 'Etymology from Remus mythological name', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00012', 'rom-', NULL, NULL, 'rom-', 'rom-', 'SC00001', 'Root meaning "of Rome", from Roma', TRUE, 'Etymology from Romulus, Romelius', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00013', 'hostil-', NULL, NULL, 'hostil-', 'hostil-', 'SC00001', 'Root meaning "hostile, enemy-like"', TRUE, 'Etymology from Hostilius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00014', 'prisc-', NULL, NULL, 'prisc-', 'prisc-', 'SC00001', 'Root meaning "ancient, old"', TRUE, 'Etymology from Priscus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00015', 'superb-', NULL, NULL, 'superb-', 'superb-', 'SC00001', 'Root meaning "proud, haughty"', TRUE, 'Etymology from Superbus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00016', 'poplic-', NULL, NULL, 'poplic-', 'poplic-', 'SC00001', 'Root meaning "of the people", from populus', TRUE, 'Etymology from Poplicola cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00017', 'sicul-', NULL, NULL, 'sicul-', 'sicul-', 'SC00001', 'Root meaning "Sicilian"', TRUE, 'Etymology from Siculus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00018', 'macer-', NULL, NULL, 'macer-', 'macer-', 'SC00001', 'Root meaning "thin, lean"', TRUE, 'Etymology from Macerinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00019', 'augur-', NULL, NULL, 'augur-', 'augur-', 'SC00001', 'Root meaning "augur, diviner"', TRUE, 'Etymology from Augurinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00020', 'camer-', NULL, NULL, 'camer-', 'camer-', 'SC00001', 'Root from Cameria, ancient Latin city', TRUE, 'Etymology from Camerinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00021', 'cornut-', NULL, NULL, 'cornut-', 'cornut-', 'SC00001', 'Root meaning "horned"', TRUE, 'Etymology from Cornutus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00022', 'iul-', NULL, NULL, 'iul-', 'iul-', 'SC00001', 'Archaic root from Iulus/Jupiter', TRUE, 'Etymology from Iullus, Julius', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00023', 'rutl-', NULL, NULL, 'rutl-', 'rutl-', 'SC00001', 'Root meaning "reddish, golden-red"', TRUE, 'Etymology from Rutilus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00024', 'vecell-', NULL, NULL, 'vecell-', 'vecell-', 'SC00001', 'Root of uncertain origin, possibly place-based', TRUE, 'Etymology from Vecellinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00025', 'mamerc-', NULL, NULL, 'mamerc-', 'mamerc-', 'SC00001', 'Oscan root related to Mars (Mamers)', TRUE, 'Etymology from Mamercus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00026', 'vibul-', NULL, NULL, 'vibul-', 'vibul-', 'SC00001', 'Root possibly from place name or estate', TRUE, 'Etymology from Vibulanus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00027', 'pulvill-', NULL, NULL, 'pulvill-', 'pulvill-', 'SC00001', 'Root meaning "little cushion"', TRUE, 'Etymology from Pulvillus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00028', 'volumn-', NULL, NULL, 'volumn-', 'volumn-', 'SC00001', 'Root from volumen or voluntas "will"', TRUE, 'Etymology from Volumnius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00029', 'alb-', NULL, NULL, 'alb-', 'alb-', 'SC00001', 'Root meaning "white, pale"', TRUE, 'Etymology from Albinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00030', 'capitol-', NULL, NULL, 'capitol-', 'capitol-', 'SC00001', 'Root meaning "of the Capitol"', TRUE, 'Etymology from Capitolinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00031', 'gemin-', NULL, NULL, 'gemin-', 'gemin-', 'SC00001', 'Root meaning "twin"', TRUE, 'Etymology from Geminus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00032', 'cicur-', NULL, NULL, 'cicur-', 'cicur-', 'SC00001', 'Root related to cicer (chickpea)', TRUE, 'Etymology from Cicurinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00033', 'sabin-', NULL, NULL, 'sabin-', 'sabin-', 'SC00001', 'Root meaning "Sabine"', TRUE, 'Etymology from Sabinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00034', 'atern-', NULL, NULL, 'atern-', 'atern-', 'SC00001', 'Root of uncertain etymology', TRUE, 'Etymology from Aternius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00035', 'romel-', NULL, NULL, 'romel-', 'romel-', 'SC00001', 'Root derived from Roma/Romulus', TRUE, 'Etymology from Romelius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00036', 'roc-', NULL, NULL, 'roc-', 'roc-', 'SC00001', 'Root of uncertain origin', TRUE, 'Etymology from Rocus name', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00037', 'vatican-', NULL, NULL, 'vatican-', 'vatican-', 'SC00001', 'Root meaning "of the Vatican Hill"', TRUE, 'Etymology from Vaticanus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00038', 'fist-', NULL, NULL, 'fist-', 'fist-', 'SC00001', 'Root related to fistula "pipe, tube"', TRUE, 'Etymology from Fistus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00039', 'curiat-', NULL, NULL, 'curiat-', 'curiat-', 'SC00001', 'Root from legendary Curiatii triplets', TRUE, 'Etymology from Curiatius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00040', 'lanat-', NULL, NULL, 'lanat-', 'lanat-', 'SC00001', 'Root meaning "woolly, fleecy"', TRUE, 'Etymology from Lanatus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00041', 'vuls-', NULL, NULL, 'vuls-', 'vuls-', 'SC00001', 'Root meaning "plucked, torn"', TRUE, 'Etymology from Vulso cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00042', 'esquilin-', NULL, NULL, 'esquilin-', 'esquilin-', 'SC00001', 'Root meaning "of the Esquiline Hill"', TRUE, 'Etymology from Esquilinus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00043', 'merend-', NULL, NULL, 'merend-', 'merend-', 'SC00001', 'Root meaning "afternoon meal"', TRUE, 'Etymology from Merenda cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00044', 'lusc-', NULL, NULL, 'lusc-', 'lusc-', 'SC00001', 'Root meaning "one-eyed"', TRUE, 'Etymology from Luscus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Praenomina Roots
('NR00045', 'gai-', NULL, NULL, 'gai-', 'gai-', 'SC00001', 'Root possibly from gaudere "to rejoice"', TRUE, 'Etymology from Gaius praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00046', 'marc-', NULL, NULL, 'marc-', 'marc-', 'SC00001', 'Root possibly from Mars, god of war', TRUE, 'Etymology from Marcus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00047', 'quint-', NULL, NULL, 'quint-', 'quint-', 'SC00001', 'Root meaning "fifth"', TRUE, 'Etymology from Quintus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00048', 'tit-', NULL, NULL, 'tit-', 'tit-', 'SC00001', 'Root possibly from titulus "title"', TRUE, 'Etymology from Titus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00049', 'aul-', NULL, NULL, 'aul-', 'aul-', 'SC00001', 'Root possibly from aula "hall"', TRUE, 'Etymology from Aulus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00050', 'app-', NULL, NULL, 'app-', 'app-', 'SC00001', 'Root associated with Claudian gens', TRUE, 'Etymology from Appius praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00051', 'decim-', NULL, NULL, 'decim-', 'decim-', 'SC00001', 'Root meaning "tenth"', TRUE, 'Etymology from Decimus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00052', 'gnae-', NULL, NULL, 'gnae-', 'gnae-', 'SC00001', 'Root possibly related to naevus "birthmark"', TRUE, 'Etymology from Gnaeus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00053', 'publ-', NULL, NULL, 'publ-', 'publ-', 'SC00001', 'Root meaning "public" or "of the people"', TRUE, 'Etymology from Publius praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00054', 'tiber-', NULL, NULL, 'tiber-', 'tiber-', 'SC00001', 'Root from river Tiber', TRUE, 'Etymology from Tiberius praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00055', 'numer-', NULL, NULL, 'numer-', 'numer-', 'SC00001', 'Root meaning "number"', TRUE, 'Etymology from Numerius praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00056', 'spur-', NULL, NULL, 'spur-', 'spur-', 'SC00001', 'Root possibly from spurius "illegitimate"', TRUE, 'Etymology from Spurius praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00057', 'sext-', NULL, NULL, 'sext-', 'sext-', 'SC00001', 'Root meaning "sixth"', TRUE, 'Etymology from Sextus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00058', 'septim-', NULL, NULL, 'septim-', 'septim-', 'SC00001', 'Root meaning "seventh"', TRUE, 'Etymology from Septimus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00059', 'anc-', NULL, NULL, 'anc-', 'anc-', 'SC00001', 'Root of uncertain etymology, possibly Etruscan', TRUE, 'Etymology from Ancus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00060', 'caes-', 'NR00001', 'semantic', 'caes-', 'caes-', 'SC00001', 'Root meaning "cut", variant used in praenomen', TRUE, 'Etymology from Caeso praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00061', 'vopisc-', NULL, NULL, 'vopisc-', 'vopisc-', 'SC00001', 'Root meaning "surviving twin"', TRUE, 'Etymology from Vopiscus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00062', 'agripp-', NULL, NULL, 'agripp-', 'agripp-', 'SC00001', 'Root meaning "born with difficulty"', TRUE, 'Etymology from Agrippa praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00063', 'opiter-', NULL, NULL, 'opiter-', 'opiter-', 'SC00001', 'Archaic root meaning "helper"', TRUE, 'Etymology from Opiter praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Nomina (Family Name) Roots
('NR00064', 'juli-', 'NR00022', 'orthographic', 'juli-', 'juli-', 'SC00001', 'Classical form of Iulus root', TRUE, 'Etymology from Julius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00065', 'fabi-', NULL, NULL, 'fabi-', 'fabi-', 'SC00001', 'Root from faba "bean"', TRUE, 'Etymology from Fabius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00066', 'anton-', NULL, NULL, 'anton-', 'anton-', 'SC00001', 'Root possibly from Greek anthos "flower"', TRUE, 'Etymology from Antonius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00067', 'aurel-', NULL, NULL, 'aurel-', 'aurel-', 'SC00001', 'Root meaning "golden"', TRUE, 'Etymology from Aurelius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00068', 'cassi-', NULL, NULL, 'cassi-', 'cassi-', 'SC00001', 'Root possibly from cassus "empty, vain"', TRUE, 'Etymology from Cassius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00069', 'flavi-', NULL, NULL, 'flavi-', 'flavi-', 'SC00001', 'Root meaning "yellow, golden"', TRUE, 'Etymology from Flavius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00070', 'tarquin-', NULL, NULL, 'tarquin-', 'tarquin-', 'SC00001', 'Root from Etruscan city Tarquinia', TRUE, 'Etymology from Tarquinius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00071', 'pompe-', NULL, NULL, 'pompe-', 'pompe-', 'SC00001', 'Root possibly from Oscan pompe "five"', TRUE, 'Etymology from Pompeius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00072', 'pompili-', NULL, NULL, 'pompili-', 'pompili-', 'SC00001', 'Root from pompa "procession"', TRUE, 'Etymology from Pompilius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00073', 'marci-', 'NR00046', 'semantic', 'marci-', 'marci-', 'SC00001', 'Root from Mars or marcus "hammer"', TRUE, 'Etymology from Marcius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00074', 'servi-', NULL, NULL, 'servi-', 'servi-', 'SC00001', 'Root meaning "to save, preserve"', TRUE, 'Etymology from Servius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00075', 'mari-', 'NR00046', 'semantic', 'mari-', 'mari-', 'SC00001', 'Root from Mars or mas "male"', TRUE, 'Etymology from Marius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00076', 'quincti-', 'NR00047', 'morphological', 'quincti-', 'quincti-', 'SC00001', 'Extended form of quint- root', TRUE, 'Etymology from Quinctius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00077', 'postum-', NULL, NULL, 'postum-', 'postum-', 'SC00001', 'Root meaning "last-born, posthumous"', TRUE, 'Etymology from Postumius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00078', 'minuc-', NULL, NULL, 'minuc-', 'minuc-', 'SC00001', 'Root possibly from minuere "to lessen"', TRUE, 'Etymology from Minucius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00079', 'sulpic-', NULL, NULL, 'sulpic-', 'sulpic-', 'SC00001', 'Root of uncertain etymology', TRUE, 'Etymology from Sulpicius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00080', 'nauti-', NULL, NULL, 'nauti-', 'nauti-', 'SC00001', 'Root from nauta "sailor"', TRUE, 'Etymology from Nautius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00081', 'aemili-', NULL, NULL, 'aemili-', 'aemili-', 'SC00001', 'Root from aemulus "rival"', TRUE, 'Etymology from Aemilius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00082', 'horati-', NULL, NULL, 'horati-', 'horati-', 'SC00001', 'Root of uncertain etymology', TRUE, 'Etymology from Horatius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00083', 'lucret-', 'NR00009', 'semantic', 'lucret-', 'lucret-', 'SC00001', 'Root from lucrum "profit, gain"', TRUE, 'Etymology from Lucretius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00084', 'quinctili-', 'NR00047', 'morphological', 'quinctili-', 'quinctili-', 'SC00001', 'Variant extended form of quint- root', TRUE, 'Etymology from Quinctilius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00085', 'furi-', NULL, NULL, 'furi-', 'furi-', 'SC00001', 'Root from furere "to rage" or furia "fury"', TRUE, 'Etymology from Furius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00086', 'larci-', NULL, NULL, 'larci-', 'larci-', 'SC00001', 'Root of uncertain origin', TRUE, 'Etymology from Larcius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00087', 'vergin-', NULL, NULL, 'vergin-', 'vergin-', 'SC00001', 'Root from virgo "maiden" or ver "spring"', TRUE, 'Etymology from Verginius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00088', 'tricost-', NULL, NULL, 'tricost-', 'tricost-', 'SC00001', 'Root meaning "three-ribbed"', TRUE, 'Etymology from Tricostus cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00089', 'valeri-', NULL, NULL, 'valeri-', 'valeri-', 'SC00001', 'Root from valere "to be strong"', TRUE, 'Etymology from Valerius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00090', 'cloeli-', NULL, NULL, 'cloeli-', 'cloeli-', 'SC00001', 'Root of uncertain origin', TRUE, 'Etymology from Cloelius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00091', 'poeteli-', NULL, NULL, 'poeteli-', 'poeteli-', 'SC00001', 'Root of uncertain etymology', TRUE, 'Etymology from Poetelius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00092', 'oppi-', NULL, NULL, 'oppi-', 'oppi-', 'SC00001', 'Root of uncertain origin', TRUE, 'Etymology from Oppius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00093', 'atili-', NULL, NULL, 'atili-', 'atili-', 'SC00001', 'Root of uncertain etymology', TRUE, 'Etymology from Atilius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Deity and Special Name Roots
('NR00094', 'termin-', NULL, NULL, 'termin-', 'termin-', 'SC00001', 'Root meaning "boundary, limit"', TRUE, 'Etymology from Terminus deity name', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00095', 'silvan-', NULL, NULL, 'silvan-', 'silvan-', 'SC00001', 'Root meaning "forest"', TRUE, 'Etymology from Silvanus deity, Silvia name', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00096', 'taruti-', NULL, NULL, 'taruti-', 'taruti-', 'SC00001', 'Root of uncertain origin', TRUE, 'Etymology from Tarutius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00097', 'jugatin-', NULL, NULL, 'jugatin-', 'jugatin-', 'SC00001', 'Root from iugum "yoke"', TRUE, 'Etymology from Jugatinus epithet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00098', 'flumine-', NULL, NULL, 'flumine-', 'flumine-', 'SC00001', 'Root meaning "of rivers"', TRUE, 'Etymology from Flumineus adjective', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00099', 'quercin-', NULL, NULL, 'quercin-', 'quercin-', 'SC00001', 'Root from quercus "oak"', TRUE, 'Etymology from Quercinus adjective', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00100', 'sciur-', NULL, NULL, 'sciur-', 'sciur-', 'SC00001', 'Root from Greek skiouros "squirrel"', TRUE, 'Etymology from Sciurinus, Sciurius cognomina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00101', 'macrob-', NULL, NULL, 'macrob-', 'macrob-', 'SC00001', 'Root from Greek makrobios "long-lived"', TRUE, 'Etymology from Macrobius name', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00102', 'virgil-', NULL, NULL, 'virgil-', 'virgil-', 'SC00001', 'Root possibly from virga "rod, staff"', TRUE, 'Etymology from Virgil (Vergilius)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00103', 'num-', NULL, NULL, 'num-', 'num-', 'SC00001', 'Root of uncertain etymology, possibly Sabine', TRUE, 'Etymology from Numa name', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00104', 'sueton-', NULL, NULL, 'sueton-', 'sueton-', 'SC00001', 'Root of uncertain origin', TRUE, 'Etymology from Suetonius nomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00105', 'varr-', NULL, NULL, 'varr-', 'varr-', 'SC00001', 'Root meaning "bow-legged"', TRUE, 'Etymology from Varro cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00106', 'tull-', NULL, NULL, 'tull-', 'tull-', 'SC00001', 'Root of uncertain etymology', TRUE, 'Etymology from Tullus praenomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00107', 'muci-', NULL, NULL, 'muci-', 'muci-', 'SC00001', 'Root possibly from muticus "docked"', TRUE, 'Etymology from Mucius nomen/cognomen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00108', 'ulyss-', NULL, NULL, 'ulyss-', 'ulyss-', 'SC00001', 'Latin form of Greek Odysseus', TRUE, 'Etymology from Ulysses (Latin form)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Greek Roots

-- Mythological Greek Roots
('NR00109', 'ἀμάλθ-', NULL, NULL, 'ἀμάλθ-', 'amalthe-', 'SC00002', 'Greek root meaning "tender", from amalthes', TRUE, 'Etymology from Amalthea (foster mother of Zeus)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00110', 'αἰγ-', NULL, NULL, 'αἰγ-', 'aig-', 'SC00002', 'Greek root meaning "goat"', TRUE, 'Etymology from Aigaion (hundred-handed one)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00111', 'ὑπέρ-', NULL, NULL, 'ὑπέρ-', 'hyper-', 'SC00002', 'Greek root meaning "over, above"', TRUE, 'Etymology from Hyperion (Titan)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00112', 'θε-', NULL, NULL, 'θε-', 'the-', 'SC00002', 'Greek root meaning "god, divine"', TRUE, 'Etymology from Theia (Titaness)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00113', 'ἀστρ-', NULL, NULL, 'ἀστρ-', 'astr-', 'SC00002', 'Greek root meaning "star"', TRUE, 'Etymology from Astraios (Titan of stars)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00114', 'κίρκ-', NULL, NULL, 'κίρκ-', 'kirk-', 'SC00002', 'Greek root possibly meaning "hawk"', TRUE, 'Etymology from Circe (enchantress)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00115', 'καλυπτ-', NULL, NULL, 'καλυπτ-', 'kalypt-', 'SC00002', 'Greek root meaning "to conceal, hide"', TRUE, 'Etymology from Calypso (sea nymph)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Historical Greek Roots  
('NR00116', 'φειδ-', NULL, NULL, 'φειδ-', 'pheid-', 'SC00002', 'Greek root meaning "to spare, be frugal"', TRUE, 'Etymology from Pheidon (king of Argos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00117', 'διόδωρ-', NULL, NULL, 'διόδωρ-', 'diodor-', 'SC00002', 'Greek compound meaning "gift of Zeus"', TRUE, 'Etymology from Diodorus (historian)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00118', 'ὀρθαγόρ-', NULL, NULL, 'ὀρθαγόρ-', 'orthagor-', 'SC00002', 'Greek compound meaning "straight speaker"', TRUE, 'Etymology from Orthagoras (tyrant of Sicyon)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00119', 'τείσανδρ-', NULL, NULL, 'τείσανδρ-', 'teisandr-', 'SC00002', 'Greek compound meaning "avenger of men"', TRUE, 'Etymology from Teisander (Greek name)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00120', 'κλεισθέν-', NULL, NULL, 'κλεισθέν-', 'kleisthen-', 'SC00002', 'Greek compound meaning "famous strength"', TRUE, 'Etymology from Cleisthenes (Athenian reformer)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00121', 'ἱπποκλείδ-', NULL, NULL, 'ἱπποκλείδ-', 'hippokeid-', 'SC00002', 'Greek compound meaning "glory of horses"', TRUE, 'Etymology from Hippocleides (Greek nobleman)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00122', 'βακχιάδ-', NULL, NULL, 'βακχιάδ-', 'bakkhiad-', 'SC00002', 'Greek patronymic from Bacchus', TRUE, 'Etymology from Bacchiadae (ruling family)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00123', 'περίανδρ-', NULL, NULL, 'περίανδρ-', 'periandr-', 'SC00002', 'Greek compound meaning "exceedingly manly"', TRUE, 'Etymology from Periander (tyrant of Corinth)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00124', 'πεισίστρατ-', NULL, NULL, 'πεισίστρατ-', 'peisistrat-', 'SC00002', 'Greek compound meaning "persuader of army"', TRUE, 'Etymology from Peisistratus (tyrant of Athens)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Philosophical Greek Roots
('NR00125', 'ἀριστοφάν-', NULL, NULL, 'ἀριστοφάν-', 'aristophan-', 'SC00002', 'Greek compound meaning "best appearing"', TRUE, 'Etymology from Aristophanes (comic playwright)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00126', 'νίκανδρ-', NULL, NULL, 'νίκανδρ-', 'nikandr-', 'SC00002', 'Greek compound meaning "victory of man"', TRUE, 'Etymology from Nicander (poet-physician)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00127', 'νικόμαχ-', NULL, NULL, 'νικόμαχ-', 'nikomakh-', 'SC00002', 'Greek compound meaning "victorious in battle"', TRUE, 'Etymology from Nicomachus (mathematician)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00128', 'φίλιππ-', NULL, NULL, 'φίλιππ-', 'philipp-', 'SC00002', 'Greek compound meaning "lover of horses"', TRUE, 'Etymology from Philip (king of Macedon)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00129', 'ἀλέξανδρ-', NULL, NULL, 'ἀλέξανδρ-', 'alexandr-', 'SC00002', 'Greek compound meaning "defender of men"', TRUE, 'Etymology from Alexander (the Great)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00130', 'ἀντίγον-', NULL, NULL, 'ἀντίγον-', 'antigon-', 'SC00002', 'Greek compound meaning "against birth"', TRUE, 'Etymology from Antigonus (successor of Alexander)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00131', 'ἀριστοτέλ-', NULL, NULL, 'ἀριστοτέλ-', 'aristotel-', 'SC00002', 'Greek compound meaning "best purpose"', TRUE, 'Etymology from Aristotle (philosopher)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00132', 'πλάτων-', NULL, NULL, 'πλάτων-', 'platon-', 'SC00002', 'Greek root meaning "broad, wide"', TRUE, 'Etymology from Plato (philosopher)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00133', 'δημόκριτ-', NULL, NULL, 'δημόκριτ-', 'demokrit-', 'SC00002', 'Greek compound meaning "chosen of people"', TRUE, 'Etymology from Democritus (atomic theorist)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00134', 'σωκράτ-', NULL, NULL, 'σωκράτ-', 'sokrat-', 'SC00002', 'Greek compound meaning "whole power"', TRUE, 'Etymology from Socrates (philosopher)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00135', 'σέλευκ-', NULL, NULL, 'σέλευκ-', 'seleuk-', 'SC00002', 'Greek root possibly meaning "white, bright"', TRUE, 'Etymology from Seleucus (founder of empire)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00136', 'πτολεμαῖ-', NULL, NULL, 'πτολεμαῖ-', 'ptolemai-', 'SC00002', 'Greek root meaning "warlike"', TRUE, 'Etymology from Ptolemy (astronomer/ruler)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00137', 'νικόδημ-', NULL, NULL, 'νικόδημ-', 'nikodem-', 'SC00002', 'Greek compound meaning "victory of people"', TRUE, 'Etymology from Nicodemus (biblical figure)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00138', 'πλωτῖν-', NULL, NULL, 'πλωτῖν-', 'plotin-', 'SC00002', 'Greek root related to wealth/riches', TRUE, 'Etymology from Plotinus (Neoplatonist)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Heroic Greek Roots
('NR00139', 'ἕκτωρ-', NULL, NULL, 'ἕκτωρ-', 'hektor-', 'SC00002', 'Greek root meaning "holding fast"', TRUE, 'Etymology from Hector (Trojan hero)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00140', 'ἀγαμέμνων-', NULL, NULL, 'ἀγαμέμνων-', 'agamemnon-', 'SC00002', 'Greek compound meaning "very resolute"', TRUE, 'Etymology from Agamemnon (Greek king)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00141', 'μενέλα-', NULL, NULL, 'μενέλα-', 'menela-', 'SC00002', 'Greek compound meaning "withstanding people"', TRUE, 'Etymology from Menelaus (Spartan king)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00142', 'ὀδυσσ-', NULL, NULL, 'ὀδυσσ-', 'odyss-', 'SC00002', 'Greek root possibly meaning "wrathful"', TRUE, 'Etymology from Odysseus (Greek hero)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00143', 'πρίαμ-', NULL, NULL, 'πρίαμ-', 'priam-', 'SC00002', 'Greek root possibly meaning "ransomed"', TRUE, 'Etymology from Priam (king of Troy)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00144', 'πάρι-', NULL, NULL, 'πάρι-', 'pari-', 'SC00002', 'Greek root of uncertain origin', TRUE, 'Etymology from Paris (Trojan prince)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00145', 'αἰνεί-', NULL, NULL, 'αἰνεί-', 'ainei-', 'SC00002', 'Greek root meaning "praised"', TRUE, 'Etymology from Aeneas (Trojan hero)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00146', 'περικλ-', NULL, NULL, 'περικλ-', 'perikl-', 'SC00002', 'Greek compound meaning "surrounded by glory"', TRUE, 'Etymology from Pericles (Athenian statesman)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00147', 'λεωνίδ-', NULL, NULL, 'λεωνίδ-', 'leonid-', 'SC00002', 'Greek compound meaning "lion-like"', TRUE, 'Etymology from Leonidas (Spartan king)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00148', 'σόλων-', NULL, NULL, 'σόλων-', 'solon-', 'SC00002', 'Greek root possibly meaning "wise"', TRUE, 'Etymology from Solon (Athenian lawgiver)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00149', 'λυκοῦργ-', NULL, NULL, 'λυκοῦργ-', 'lykoyrg-', 'SC00002', 'Greek compound meaning "wolf-worker"', TRUE, 'Etymology from Lycurgus (Spartan lawgiver)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00150', 'ἑλέν-', NULL, NULL, 'ἑλέν-', 'helen-', 'SC00002', 'Greek root possibly meaning "torch, light"', TRUE, 'Etymology from Helen (of Troy)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Additional Greek Compound Roots
('NR00151', 'δημήτρι-', NULL, NULL, 'δημήτρι-', 'demetri-', 'SC00002', 'Greek compound meaning "follower of Demeter"', TRUE, 'Etymology from Demetrius (various rulers)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00152', 'κάσσανδρ-', NULL, NULL, 'κάσσανδρ-', 'kassandr-', 'SC00002', 'Greek compound meaning "helper of men"', TRUE, 'Etymology from Cassander (Macedonian king)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00153', 'λύσανδρ-', NULL, NULL, 'λύσανδρ-', 'lysandr-', 'SC00002', 'Greek compound meaning "liberator of men"', TRUE, 'Etymology from Lysander (Spartan general)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00154', 'ἀντίοχ-', NULL, NULL, 'ἀντίοχ-', 'antiokh-', 'SC00002', 'Greek compound meaning "resistant"', TRUE, 'Etymology from Antiochus (Seleucid kings)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00155', 'πολύβι-', NULL, NULL, 'πολύβι-', 'polybi-', 'SC00002', 'Greek compound meaning "much life"', TRUE, 'Etymology from Polybius (historian)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00156', 'βελισάρι-', NULL, NULL, 'βελισάρι-', 'belisari-', 'SC00002', 'Greek root of uncertain origin', TRUE, 'Etymology from Belisarius (Byzantine general)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00157', 'θεοδώρ-', NULL, NULL, 'θεοδώρ-', 'theodor-', 'SC00002', 'Greek compound meaning "gift of God"', TRUE, 'Etymology from Theodora (Byzantine empress)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00158', 'παρμενίων-', NULL, NULL, 'παρμενίων-', 'parmenion-', 'SC00002', 'Greek root meaning "constant"', TRUE, 'Etymology from Parmenion (Macedonian general)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00159', 'ἡφαιστίων-', NULL, NULL, 'ἡφαιστίων-', 'hephaestion-', 'SC00002', 'Greek compound meaning "of Hephaestus"', TRUE, 'Etymology from Hephaestion (companion of Alexander)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00160', 'πολύδωρ-', NULL, NULL, 'πολύδωρ-', 'polydor-', 'SC00002', 'Greek compound meaning "many gifts"', TRUE, 'Etymology from Polydorus (son of Priam)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Common Greek Root Components
('NR00161', 'κλε-', NULL, NULL, 'κλε-', 'kle-', 'SC00002', 'Greek root meaning "glory, fame"', TRUE, 'Common component in Greek names (kleos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00162', 'ἀνδρ-', NULL, NULL, 'ἀνδρ-', 'andr-', 'SC00002', 'Greek root meaning "man"', TRUE, 'Common component in Greek names (aner/andros)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00163', 'νικ-', NULL, NULL, 'νικ-', 'nik-', 'SC00002', 'Greek root meaning "victory"', TRUE, 'Common component in Greek names (nike)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00164', 'φιλ-', NULL, NULL, 'φιλ-', 'phil-', 'SC00002', 'Greek root meaning "loving, friend"', TRUE, 'Common component in Greek names (philos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00165', 'δημ-', NULL, NULL, 'δημ-', 'dem-', 'SC00002', 'Greek root meaning "people"', TRUE, 'Common component in Greek names (demos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00166', 'στρατ-', NULL, NULL, 'στρατ-', 'strat-', 'SC00002', 'Greek root meaning "army"', TRUE, 'Common component in Greek names (stratos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00167', 'λα-', NULL, NULL, 'λα-', 'la-', 'SC00002', 'Greek root meaning "people" (poetic)', TRUE, 'Common component in Greek names (laos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00168', 'δωρ-', NULL, NULL, 'δωρ-', 'dor-', 'SC00002', 'Greek root meaning "gift"', TRUE, 'Common component in Greek names (doron)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00169', 'μαχ-', NULL, NULL, 'μαχ-', 'makh-', 'SC00002', 'Greek root meaning "battle"', TRUE, 'Common component in Greek names (mache)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NR00170', 'γεν-', NULL, NULL, 'γεν-', 'gen-', 'SC00002', 'Greek root meaning "birth, race"', TRUE, 'Common component in Greek names (genos)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);